// Uji end-to-end API backend (jalan sekali, lalu hapus)
const B = 'http://localhost:3001';
const ok = (label, val) => console.log('✔', label, val);
const post = (p, body) => fetch(B + p, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body || {}) }).then(async (r) => { const j = await r.json(); if (!r.ok) throw new Error(p + ' ' + r.status + ' ' + JSON.stringify(j)); return j; });
const get = (p) => fetch(B + p).then(async (r) => { const j = await r.json(); if (!r.ok) throw new Error(p + ' ' + r.status + ' ' + JSON.stringify(j)); return j; });

const h = await get('/api/health');
ok('health', JSON.stringify(h));
const c = await post('/api/career', { managerName: 'Tester', clubId: 1 });
ok('career', `${c.save.club.name} budget=${c.save.budget} lineup=${c.save.lineup.length}`);
const p1 = await post('/api/play', { phase: 'first' });
ok('play1', `${p1.userResult.homeName} ${p1.userResult.homeGoals}-${p1.userResult.awayGoals} ${p1.userResult.awayName} | others=${p1.others.length} ms=${p1.ms}`);
const p2 = await post('/api/play', { phase: 'second', halfTimeState: p1.halfTimeState });
ok('play2', `FT ${p2.userResult.homeGoals}-${p2.userResult.awayGoals} nextMD=${p2.nextMatchday} ms=${p2.ms}`);
const s = await get('/api/state');
ok('state', `md=${s.save.matchday} club=${s.save.club.name} logo=${s.save.club.logo_url}`);
const st = await get('/api/standings');
ok('standings', `top=${st[0].name} P=${st[0].played} pts=${st[0].points} gd=${st[0].gd} (${st.length} rows)`);
const sq = await get('/api/squad');
ok('squad', `${sq.length} pemain, ovr-top=${sq[0].ovr}`);
const tl = await get('/api/transfer-list');
ok('transfer-list', `${tl.length} pemain, target=${tl[0].name}`);
const b = await post('/api/transfer/buy', { playerId: tl[0].id });
ok('buy', `budget=${b.save.budget}`);
const mine = await get('/api/squad');
const last = mine[mine.length - 1];
const sel = await post('/api/transfer/sell', { playerId: last.id });
ok('sell', `${last.name} budget=${sel.save.budget}`);
const t = await post('/api/tactics', { formation: '4-3-3', mentality: 'attacking' });
ok('tactics', `${t.save.formation}/${t.save.mentality} lineup=${t.save.lineup.length}`);
const out = t.save.lineup[0];
const inn = mine.map((p) => p.id).find((id) => !t.save.lineup.includes(id) && id !== out);
const sub = await post('/api/sub', { outId: out, inId: inn });
ok('sub', `lineup=${sub.save.lineup.length}`);
const f = await get('/api/next-fixture');
ok('next-fixture', f.finished ? 'season done' : `MD${f.matchday}: ${f.home.short_name} vs ${f.away.short_name}`);
const fx = await get('/api/fixtures?matchday=1');
ok('fixtures', `${fx.length} laga MD1`);
const n = await get('/api/news');
ok('news', `top="${n[0].title}" (${n.length} item)`);
console.log('\nSEMUA TES LULUS 🎉');